package br.com.models;
// Generated 27/11/2015 18:16:50 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Pessoa generated by hbm2java
 */
@Entity
@Table(name = "pessoa")
public class Pessoa  implements java.io.Serializable {


    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @OneToOne
    @JoinColumn(name = "idEndereco")
    private Endereco endereco;

    @Column(name = "nome")
    private String nome;

    @Column(name = "cpf")
    private Long cpf;

    @Column(name = "nascimento")
    private Date nascimento;
     
     
    public Pessoa() {
    }

	
    public Pessoa(Long id) {
        this.id = id;
    }
    public Pessoa(Long id, Endereco endereco, String nome, Long cpf, Date nascimento) {
       this.id = id;
       this.endereco = endereco;
       this.nome = nome;
       this.cpf = cpf;
       this.nascimento = nascimento;
    }
   
    public Long getIdPessoa() {
        return this.id;
    }
    
    public void setIdPessoa(Long id) {
        this.id = id;
    }
    public Endereco getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Long getCpf() {
        return this.cpf;
    }
    
    public void setCpf(Long cpf) {
        this.cpf = cpf;
    }
    public Date getNascimento() {
        return this.nascimento;
    }
    
    public void setNascimento(Date nascimento) {
        this.nascimento = nascimento;
    }
    public Long getIdUsuario() {
        return this.id;
    }
    
    public void setIdUsuario(Long id) {
        this.id = id;
    }




}


